language: r
warnings_are_errors: true
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
  - master

after_failure:
  - Rscript -e 'install.packages("devtools");devtools::install();devtools::test()'
  